apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole
spec:
  ingressClassName: nginx
  rules:
  - host: guacamole.hongphucvu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole
            port:
              number: 8080